package group3.project.test.model;

import javax.persistence.*;


@Entity
@Table(name = "student", uniqueConstraints = @UniqueConstraint(columnNames = {"student_address"}))
public class student {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)//##Make the id autogenerated by the databse
    int student_id;     

    @Column(nullable = false, length = 45)
    String student_name;
    
    String student_address;

    @Column(nullable = false, unique = true, length = 45)
    String student_email;

    @Column(nullable = false, length = 64)
    String student_password;    

    public student() {
    }

    public student(String student_name, String student_address, String student_email, String student_password) {
        this.student_name = student_name;
        this.student_address = student_address;
        this.student_email = student_email;
        this.student_password = student_password;
    }

    public int getStudent_id() {
        return student_id;
    }

    public void setStudent_id(int student_id) {
        this.student_id = student_id;
    }

    public String getStudent_name() {
        return student_name;
    }

    public void setStudent_name(String student_name) {
        this.student_name = student_name;
    }

    public String getStudent_address() {
        return student_address;
    }

    public void setStudent_address(String student_address) {
        this.student_address = student_address;
    }

    public String getStudent_email() {
        return student_email;
    }

    public void setStudent_email(String student_email) {
        this.student_email = student_email;
    }

    public String getStudent_password() {
        return student_password;
    }

    public void setStudent_password(String student_password) {
        this.student_password = student_password;
    }

    
    
}
